import jsPDF from 'jspdf';

interface ProfileData {
  name: string;
  education: string;
  skills: string;
  location: string;
  sector: string;
  gender: string;
  age: string;
}

export const generateResumePDF = async (profileData: ProfileData): Promise<void> => {
  const doc = new jsPDF();
  
  // Set font
  doc.setFont('helvetica');
  
  // Header
  doc.setFontSize(24);
  doc.setTextColor(33, 150, 243); // Primary blue color
  doc.text(profileData.name || 'Your Name', 20, 30);
  
  // Contact Info
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`${profileData.location} | Age: ${profileData.age}`, 20, 40);
  doc.text('Generated via InternConnect - Government Internship Portal', 20, 45);
  
  // Horizontal line
  doc.setDrawColor(200, 200, 200);
  doc.line(20, 50, 190, 50);
  
  // Objective Section
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('OBJECTIVE', 20, 65);
  
  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  const objective = `Motivated ${profileData.education} student seeking government internship opportunities in ${profileData.sector} sector to contribute to national development and gain practical experience.`;
  
  const objectiveLines = doc.splitTextToSize(objective, 150);
  doc.text(objectiveLines, 20, 75);
  
  let yPosition = 75 + (objectiveLines.length * 5) + 10;
  
  // Education Section
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('EDUCATION', 20, yPosition);
  yPosition += 10;
  
  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  doc.text(`${profileData.education}`, 20, yPosition);
  doc.text('Currently Pursuing', 20, yPosition + 5);
  yPosition += 20;
  
  // Skills Section
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('SKILLS', 20, yPosition);
  yPosition += 10;
  
  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  const skillsList = profileData.skills ? profileData.skills.split(',').map(s => s.trim()) : ['Communication', 'Teamwork', 'Problem Solving'];
  
  skillsList.forEach((skill, index) => {
    if (skill) {
      doc.text(`• ${skill}`, 25, yPosition);
      yPosition += 5;
    }
  });
  
  yPosition += 10;
  
  // Interests Section
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('AREAS OF INTEREST', 20, yPosition);
  yPosition += 10;
  
  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  doc.text(`• ${profileData.sector} and Government Policy`, 25, yPosition);
  doc.text('• Rural Development and Digital Inclusion', 25, yPosition + 5);
  doc.text('• Public Service and Social Impact', 25, yPosition + 10);
  yPosition += 25;
  
  // Experience Section (Template)
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('EXPERIENCE / PROJECTS', 20, yPosition);
  yPosition += 10;
  
  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  doc.text('• Academic Projects and Coursework', 25, yPosition);
  doc.text('• Community Service and Volunteer Work', 25, yPosition + 5);
  doc.text('• Ready to contribute to government initiatives', 25, yPosition + 10);
  yPosition += 25;
  
  // Languages
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('LANGUAGES', 20, yPosition);
  yPosition += 10;
  
  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  doc.text('• Hindi (Native/Fluent)', 25, yPosition);
  doc.text('• English (Proficient)', 25, yPosition + 5);
  
  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by InternConnect | Government Internship Portal', 20, 280);
  doc.text(new Date().toLocaleDateString(), 20, 285);
  
  // Save the PDF
  const fileName = `${profileData.name || 'Resume'}_InternConnect.pdf`;
  doc.save(fileName);
};

export const generateCoverLetter = (profileData: ProfileData, internshipTitle: string = 'Government Internship'): string => {
  return `Dear Hiring Manager,

I am writing to express my strong interest in the ${internshipTitle} position. As a ${profileData.education} student with a passion for ${profileData.sector}, I am eager to contribute to government initiatives that serve our nation.

My background in ${profileData.education} has equipped me with ${profileData.skills || 'relevant skills'}, which align well with the requirements of this internship. I am particularly drawn to opportunities that allow me to apply my knowledge while learning about government operations and public service.

As someone from ${profileData.location}, I understand the importance of government programs in rural and urban development. I am committed to contributing to initiatives that make a positive impact on society and help bridge the digital divide.

I am excited about the opportunity to learn from experienced professionals and contribute fresh perspectives to your team. Thank you for considering my application.

Sincerely,
${profileData.name}

---
Generated via InternConnect - Government Internship Portal
`;
};